// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svnxsmvfsnixakbgfahp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2bnhzbXZmc25peGFrYmdmYWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNTM4NjYsImV4cCI6MjA3NzkyOTg2Nn0.6E7G6AM2VYWItrLq8CSet1PyEyDn9tqu0porxbVUL2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});